# Generated by Django 3.0.6 on 2020-05-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
